### ISSUE TITLE
Error starting built mod using expandability as a dependency

### ISSUE THREAD

**Issue by Kuikenpower35** [florensie/swimmies#8]
So I have a mod that adds a few items to minecraft. When starting it in my ide(eclipse) using runClient it works perfectly fine, but if I build it to a jar file and start it with the minecraft launcher I get an error that mentions this dependency. How would I fix this? Thanks in advance!
[crash-2023-06-22_16.48.24-fml.txt](https://github.com/florensie/ExpandAbility/files/11835378/crash-2023-06-22_16.48.24-fml.txt)

**Comment by florensie** [comment]
Your log suggests expandability is not on your runtime classpath, and does not show in the modlist. Make sure that you have the expandability jar in your mods folder, [or include it in your mod as a JarJar dependency](https://github.com/ochotonida/artifacts/blob/2fd95847c42774ea67648611e15cec05ee02bb67/build.gradle#L102).

Also, you should [add the dependency to your mods.toml](https://github.com/ochotonida/artifacts/blob/1.19.x/src/main/resources/META-INF/mods.toml#L35) so your users get a clear error message if it is missing instead of this crash.

**Comment by Kuikenpower35** [comment]
Thanks for the quick answer, though I do have expandability 7.0.0 installed. Is there something else you think could be wrong? I will also try to redownload it tomorrow just to be sure.

**Comment by Kuikenpower35** [comment]
You have stupid people and then you have me... I downloaded the fabric version by accident, while I am using forge. Thanks for your answer anyway and sorry to take up your time!
